-- ====================================================================
-- GANESHSTORE ENTERPRISE SUPABASE DATABASE MIGRATION & SCHEMA
-- ====================================================================
-- Version: 3.0.0 (Hardened RLS, Server-Side Pricing, 2FA Encryption)
-- Description: Complete enterprise database schema for GaneshStore with
-- least-privilege Row-Level Security, atomic Postgres RPCs for pricing,
-- order authority, coupon validation, pgcrypto 2FA encryption, and seed data.
-- ====================================================================

-- 0. Helper Functions & Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ====================================================================
-- 1. Profiles Table (User Accounts, Loyalty Points, Tiers & 2FA)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    full_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone_number TEXT,
    loyalty_tier TEXT DEFAULT 'Bronze' CHECK (loyalty_tier IN ('Bronze', 'Silver', 'Gold', 'Platinum')),
    loyalty_points INTEGER DEFAULT 100,
    two_factor_enabled BOOLEAN DEFAULT false,
    two_factor_secret TEXT,
    avatar_url TEXT,
    default_address JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Hardened RLS: Users can only view and mutate their own profile row
CREATE POLICY "Users can view their own profile only" ON public.profiles
    FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can insert their own profile only" ON public.profiles
    FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update their own profile only" ON public.profiles
    FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE POLICY "Service role has full access to profiles" ON public.profiles
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE TRIGGER set_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);
CREATE INDEX IF NOT EXISTS idx_profiles_phone ON public.profiles(phone_number);


-- ====================================================================
-- 2. Products Catalog Table
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    original_price NUMERIC(10, 2),
    category TEXT NOT NULL,
    subcategory TEXT,
    tags TEXT[] DEFAULT ARRAY[]::TEXT[],
    rating NUMERIC(3, 2) DEFAULT 5.00,
    reviews_count INTEGER DEFAULT 0,
    images JSONB DEFAULT '[]'::jsonb,
    sizes TEXT[] DEFAULT ARRAY['S', 'M', 'L', 'XL']::TEXT[],
    colors TEXT[] DEFAULT ARRAY['Default']::TEXT[],
    stock_quantity INTEGER DEFAULT 50,
    is_featured BOOLEAN DEFAULT false,
    is_trending BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Hardened RLS: Public READ-ONLY access. Mutations restricted to admin/service role
CREATE POLICY "Products are publicly readable by everyone" ON public.products
    FOR SELECT USING (true);

CREATE POLICY "Only admin or service role can mutate products" ON public.products
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role' OR auth.jwt() ->> 'role' = 'admin');

CREATE TRIGGER set_products_updated_at
    BEFORE UPDATE ON public.products
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);


-- ====================================================================
-- 3. Product Reviews Table
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT REFERENCES public.products(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    reviewer_name TEXT NOT NULL,
    email TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT NOT NULL,
    verified_purchase BOOLEAN DEFAULT true,
    helpful_votes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reviews are viewable by everyone" ON public.reviews
    FOR SELECT USING (true);

CREATE POLICY "Users can submit product reviews" ON public.reviews
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Only admin or service role can delete/update reviews" ON public.reviews
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role' OR auth.jwt() ->> 'role' = 'admin');

CREATE INDEX IF NOT EXISTS idx_reviews_product_name ON public.reviews(product_name);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews(product_id);


-- ====================================================================
-- 4. Carts Table (Cloud Persistent Shopping Carts)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,
    items JSONB DEFAULT '[]'::jsonb NOT NULL,
    subtotal NUMERIC(10, 2) DEFAULT 0.00,
    total NUMERIC(10, 2) DEFAULT 0.00,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;

-- Hardened RLS: Users can only view and manage their own cart
CREATE POLICY "Users can view and manage their own cart only" ON public.carts
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Service role has full access to carts" ON public.carts
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE TRIGGER set_carts_updated_at
    BEFORE UPDATE ON public.carts
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_carts_user_id ON public.carts(user_id);


-- ====================================================================
-- 5. Wishlists Table (Cloud Persistent Wishlists)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,
    items JSONB DEFAULT '[]'::jsonb NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;

-- Hardened RLS: Users can only view and manage their own wishlist
CREATE POLICY "Users can view and manage their own wishlist only" ON public.wishlists
    FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Service role has full access to wishlists" ON public.wishlists
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE TRIGGER set_wishlists_updated_at
    BEFORE UPDATE ON public.wishlists
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_wishlists_user_id ON public.wishlists(user_id);


-- ====================================================================
-- 6. Orders Table (E-commerce Checkout & Live Tracking)
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    shipping_address TEXT NOT NULL,
    shipping_method TEXT DEFAULT 'Standard Delivery' NOT NULL,
    payment_method TEXT DEFAULT 'CARD' NOT NULL,
    payment_status TEXT DEFAULT 'COMPLETED' CHECK (payment_status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    order_status TEXT DEFAULT 'processing' CHECK (order_status IN ('placed', 'processing', 'shipped', 'out_for_delivery', 'delivered', 'cancelled')),
    tracking_number TEXT,
    estimated_delivery DATE,
    items JSONB NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    discount NUMERIC(10, 2) DEFAULT 0.00 NOT NULL,
    shipping_fee NUMERIC(10, 2) DEFAULT 0.00 NOT NULL,
    tax NUMERIC(10, 2) DEFAULT 0.00 NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Hardened RLS: Users can only see their own orders; mutations via RPC or service role
CREATE POLICY "Users can view their own orders only" ON public.orders
    FOR SELECT USING (auth.uid() = user_id OR auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Authorized order creation" ON public.orders
    FOR INSERT WITH CHECK (auth.uid() = user_id OR user_id IS NULL OR auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Only service role can update orders" ON public.orders
    FOR UPDATE USING (auth.jwt() ->> 'role' = 'service_role');

CREATE TRIGGER set_orders_updated_at
    BEFORE UPDATE ON public.orders
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_orders_order_id ON public.orders(order_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_email ON public.orders(email);


-- ====================================================================
-- 7. Newsletter Subscribers Table
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    source TEXT DEFAULT 'footer_newsletter',
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'unsubscribed')),
    subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can subscribe to newsletter" ON public.newsletter_subscribers
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Only service role can read newsletter subscribers" ON public.newsletter_subscribers
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE INDEX IF NOT EXISTS idx_newsletter_email ON public.newsletter_subscribers(email);


-- ====================================================================
-- 8. Contact Inquiries / Messages Table
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'unread' CHECK (status IN ('unread', 'read', 'replied')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can submit contact message" ON public.contact_messages
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Only service role can read contact messages" ON public.contact_messages
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');


-- ====================================================================
-- 9. Coupons & Promotions Table
-- ====================================================================
CREATE TABLE IF NOT EXISTS public.coupons (
    code TEXT PRIMARY KEY,
    discount_type TEXT DEFAULT 'percentage' CHECK (discount_type IN ('percentage', 'fixed', 'free_shipping')),
    discount_value NUMERIC(10, 2) NOT NULL,
    min_order_amount NUMERIC(10, 2) DEFAULT 0.00,
    max_discount NUMERIC(10, 2),
    is_active BOOLEAN DEFAULT true,
    valid_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Active coupons are viewable" ON public.coupons
    FOR SELECT USING (is_active = true AND (valid_until IS NULL OR valid_until > NOW()));

CREATE POLICY "Only service role or admin can manage coupons" ON public.coupons
    FOR ALL USING (auth.jwt() ->> 'role' = 'service_role' OR auth.jwt() ->> 'role' = 'admin');


-- ====================================================================
-- 10. ATOMIC POSTGRES RPC FUNCTIONS (Server-Side Pricing & 2FA)
-- ====================================================================

-- RPC 1: Authoritative Server-Side Coupon Validation
CREATE OR REPLACE FUNCTION public.validate_coupon_code(
    coupon_code TEXT,
    subtotal_amount NUMERIC DEFAULT 0.00
)
RETURNS JSONB AS $$
DECLARE
    found_coupon RECORD;
    computed_discount NUMERIC(10, 2) := 0.00;
BEGIN
    SELECT * INTO found_coupon 
    FROM public.coupons 
    WHERE UPPER(code) = UPPER(TRIM(coupon_code))
      AND is_active = true
      AND (valid_until IS NULL OR valid_until > NOW());

    IF NOT FOUND THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message', 'Invalid or expired promo code.'
        );
    END IF;

    IF subtotal_amount < found_coupon.min_order_amount THEN
        RETURN jsonb_build_object(
            'valid', false,
            'message', format('Minimum order amount of $%s required for this coupon.', found_coupon.min_order_amount)
        );
    END IF;

    IF found_coupon.discount_type = 'percentage' THEN
        computed_discount := ROUND((subtotal_amount * (found_coupon.discount_value / 100.0)), 2);
        IF found_coupon.max_discount IS NOT NULL AND computed_discount > found_coupon.max_discount THEN
            computed_discount := found_coupon.max_discount;
        END IF;
    ELSIF found_coupon.discount_type = 'fixed' THEN
        computed_discount := LEAST(found_coupon.discount_value, subtotal_amount);
    ELSIF found_coupon.discount_type = 'free_shipping' THEN
        computed_discount := 0.00;
    END IF;

    RETURN jsonb_build_object(
        'valid', true,
        'code', found_coupon.code,
        'discount_type', found_coupon.discount_type,
        'discount_value', found_coupon.discount_value,
        'discount_amount', computed_discount,
        'message', 'Promo code applied successfully.'
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC 2: Atomic Server-Side Order Pricing & Placement
CREATE OR REPLACE FUNCTION public.create_authenticated_order(
    order_payload JSONB
)
RETURNS JSONB AS $$
DECLARE
    item_elem JSONB;
    p_id TEXT;
    p_qty INTEGER;
    db_product RECORD;
    computed_subtotal NUMERIC(10, 2) := 0.00;
    computed_discount NUMERIC(10, 2) := 0.00;
    computed_shipping NUMERIC(10, 2) := 0.00;
    computed_tax NUMERIC(10, 2) := 0.00;
    computed_total NUMERIC(10, 2) := 0.00;
    
    in_coupon_code TEXT;
    coupon_res JSONB;
    
    new_order_id TEXT;
    new_tracking_no TEXT;
    est_delivery DATE;
    verified_items JSONB := '[]'::jsonb;
BEGIN
    -- 1. Validate items and calculate subtotal authoritatively from DB prices
    FOR item_elem IN SELECT * FROM jsonb_array_elements(order_payload->'items')
    LOOP
        p_id := item_elem->>'id';
        p_qty := COALESCE((item_elem->>'quantity')::INTEGER, (item_elem->>'qty')::INTEGER, 1);
        
        -- Lookup product by id or fallback by name
        SELECT * INTO db_product FROM public.products WHERE id = p_id OR name = (item_elem->>'name') LIMIT 1;
        
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Product not found in store catalog: %', COALESCE(p_id, item_elem->>'name');
        END IF;

        IF db_product.stock_quantity < p_qty THEN
            RAISE EXCEPTION 'Insufficient stock for % (Requested: %, Available: %)', db_product.name, p_qty, db_product.stock_quantity;
        END IF;

        computed_subtotal := computed_subtotal + (db_product.price * p_qty);

        -- Build verified item payload with DB authoritative price
        verified_items := verified_items || jsonb_build_object(
            'id', db_product.id,
            'name', db_product.name,
            'price', db_product.price,
            'quantity', p_qty,
            'size', COALESCE(item_elem->>'size', 'M'),
            'color', COALESCE(item_elem->>'color', 'Default'),
            'image', COALESCE(item_elem->>'image', (db_product.images->0->>'url'), 'images/product-01.jpg')
        );
    END LOOP;

    -- 2. Validate and apply coupon server-side
    in_coupon_code := TRIM(COALESCE(order_payload->>'coupon_code', ''));
    IF in_coupon_code <> '' THEN
        coupon_res := public.validate_coupon_code(in_coupon_code, computed_subtotal);
        IF (coupon_res->>'valid')::BOOLEAN THEN
            computed_discount := (coupon_res->>'discount_amount')::NUMERIC;
        END IF;
    END IF;

    -- 3. Calculate shipping & tax
    IF (order_payload->>'shipping_method') = 'Express Delivery' THEN
        computed_shipping := 15.00;
    ELSIF computed_subtotal >= 100.00 OR (coupon_res IS NOT NULL AND coupon_res->>'discount_type' = 'free_shipping') THEN
        computed_shipping := 0.00;
    ELSE
        computed_shipping := 9.99;
    END IF;

    computed_tax := 0.00;
    computed_total := GREATEST(0.00, computed_subtotal - computed_discount) + computed_shipping + computed_tax;

    -- 4. Generate order identifiers & estimated delivery
    new_order_id := 'ORD-' || FLOOR(100000 + RANDOM() * 900000)::TEXT;
    new_tracking_no := 'GS-TRK-' || FLOOR(10000000 + RANDOM() * 90000000)::TEXT;
    
    IF (order_payload->>'shipping_method') = 'Express Delivery' THEN
        est_delivery := CURRENT_DATE + INTERVAL '2 days';
    ELSE
        est_delivery := CURRENT_DATE + INTERVAL '4 days';
    END IF;

    -- 5. Insert order atomically into orders table
    INSERT INTO public.orders (
        order_id,
        user_id,
        customer_name,
        email,
        phone,
        shipping_address,
        shipping_method,
        payment_method,
        payment_status,
        order_status,
        tracking_number,
        estimated_delivery,
        items,
        subtotal,
        discount,
        shipping_fee,
        tax,
        total,
        notes
    ) VALUES (
        new_order_id,
        CASE WHEN (order_payload->>'user_id') IS NOT NULL AND (order_payload->>'user_id') ~ '^[0-9a-fA-F-]{36}$' THEN (order_payload->>'user_id')::UUID ELSE NULL END,
        COALESCE(order_payload->>'customer_name', 'Guest Customer'),
        COALESCE(order_payload->>'email', 'customer@ganeshstore.com'),
        order_payload->>'phone',
        COALESCE(order_payload->>'shipping_address', '123 Luxury Lane, New York, NY'),
        COALESCE(order_payload->>'shipping_method', 'Standard Delivery'),
        COALESCE(UPPER(order_payload->>'payment_method'), 'CARD'),
        'COMPLETED',
        'processing',
        new_tracking_no,
        est_delivery,
        verified_items,
        computed_subtotal,
        computed_discount,
        computed_shipping,
        computed_tax,
        computed_total,
        order_payload->>'notes'
    );

    RETURN jsonb_build_object(
        'success', true,
        'order_id', new_order_id,
        'tracking_number', new_tracking_no,
        'subtotal', computed_subtotal,
        'discount', computed_discount,
        'shipping_fee', computed_shipping,
        'tax', computed_tax,
        'total', computed_total,
        'estimated_delivery', to_char(est_delivery, 'Dy, Mon DD, YYYY')
    );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- RPC 3: Encrypted 2FA Secret Storage & Verification Helpers
CREATE OR REPLACE FUNCTION public.enable_user_2fa(
    p_user_id UUID,
    p_secret_text TEXT,
    p_encryption_key TEXT DEFAULT 'ganeshstore_totp_secure_vault_key'
)
RETURNS JSONB AS $$
BEGIN
    UPDATE public.profiles
    SET two_factor_enabled = true,
        two_factor_secret = pgp_sym_encrypt(p_secret_text, p_encryption_key)::TEXT,
        updated_at = TIMEZONE('utc'::text, NOW())
    WHERE id = p_user_id;

    RETURN jsonb_build_object('success', true, 'message', '2FA enabled with pgcrypto encryption at rest.');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_decrypted_2fa_secret(
    p_user_id UUID,
    p_encryption_key TEXT DEFAULT 'ganeshstore_totp_secure_vault_key'
)
RETURNS TEXT AS $$
DECLARE
    raw_val TEXT;
    decrypted TEXT;
BEGIN
    SELECT two_factor_secret INTO raw_val FROM public.profiles WHERE id = p_user_id;
    
    IF raw_val IS NULL THEN
        RETURN NULL;
    END IF;

    -- If secret was encrypted via pgp_sym_encrypt
    IF raw_val LIKE '\x%' OR raw_val LIKE '-----BEGIN PGP MESSAGE%' THEN
        BEGIN
            decrypted := pgp_sym_decrypt(raw_val::bytea, p_encryption_key);
            RETURN decrypted;
        EXCEPTION WHEN OTHERS THEN
            RETURN raw_val;
        END;
    END IF;

    RETURN raw_val;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ====================================================================
-- INITIAL SEED DATA
-- ====================================================================

-- Seed Coupons
INSERT INTO public.coupons (code, discount_type, discount_value, min_order_amount, is_active) VALUES
    ('SAVE10', 'percentage', 10.00, 0.00, true),
    ('GANESH20', 'fixed', 20.00, 50.00, true),
    ('WELCOME10', 'percentage', 10.00, 0.00, true),
    ('FREESHIP', 'free_shipping', 0.00, 0.00, true)
ON CONFLICT (code) DO UPDATE SET is_active = true;

-- Seed Master Products
INSERT INTO public.products (id, name, slug, description, price, category, tags, rating, reviews_count, images, is_featured, is_trending) VALUES
    ('GS001', 'Esprit Ruffle Shirt', 'p-Esprit-Ruffle-Shirt', 'Ultra-breathable premium cotton ruffle shirt with meticulous stitching and modern relaxed fit.', 16.64, 'Women', ARRAY['women', 'fashion', 'shirt'], 4.90, 28, '[{"url": "images/product-01.jpg"}]'::jsonb, true, true),
    ('GS002', 'Herschel supply', 'p-Herschel-supply', 'Iconic minimalist everyday essential tailored for effortless style and maximum comfort.', 35.31, 'Women', ARRAY['women', 'fashion', 'top'], 4.80, 19, '[{"url": "images/product-02.jpg"}]'::jsonb, true, false),
    ('GS003', 'Only Check Trouser', 'p-Only-Check-Trouser', 'Tailored check trousers crafted from premium stretch fabric for smart-casual and formal elegance.', 25.50, 'Men', ARRAY['men', 'trouser', 'pants'], 4.85, 24, '[{"url": "images/product-03.jpg"}]'::jsonb, false, true),
    ('GS004', 'Classic Trench Coat', 'p-Classic-Trench-Coat', 'Signature double-breasted weatherproof trench coat with premium storm flap and waist belt.', 75.00, 'Women', ARRAY['women', 'coat', 'jacket'], 5.00, 42, '[{"url": "images/product-04.jpg"}]'::jsonb, true, true),
    ('GS005', 'Front Pocket Jumper', 'p-Front-Pocket-Jumper', 'Cozy knit jumper with front utility pocket detailing and ribbed cuff trims.', 34.75, 'Women', ARRAY['women', 'jumper', 'knitwear'], 4.75, 15, '[{"url": "images/product-05.jpg"}]'::jsonb, false, false),
    ('GS006', 'Vintage Inspired Classic', 'p-Vintage-Inspired-Classic', 'Timeless chronometer watch with genuine Italian leather strap and scratch-resistant sapphire crystal.', 93.20, 'Watches', ARRAY['watches', 'accessories', 'luxury'], 4.95, 36, '[{"url": "images/product-06.jpg"}]'::jsonb, true, true),
    ('GS007', 'Shirt in Stretch Cotton', 'p-Shirt-in-Stretch-Cotton', 'Refined stretch cotton button-up shirt engineered for clean lines and all-day flexibility.', 52.66, 'Women', ARRAY['women', 'shirt', 'formal'], 4.70, 11, '[{"url": "images/product-07.jpg"}]'::jsonb, false, false),
    ('GS008', 'Pieces Metallic Printed', 'p-Pieces-Metallic-Printed', 'Shimmering metallic printed party top designed for statement evening occasions.', 18.96, 'Women', ARRAY['women', 'top', 'metallic'], 4.65, 8, '[{"url": "images/product-08.jpg"}]'::jsonb, false, false),
    ('GS009', 'Converse All Star Hi Plimsolls', 'p-Converse-All-Star-Hi-Plimsolls', 'High-top canvas sneaker classic with vulcanized rubber sole and vintage ankle patch.', 75.00, 'Shoes', ARRAY['shoes', 'sneakers', 'footwear'], 4.90, 53, '[{"url": "images/product-09.jpg"}]'::jsonb, true, true),
    ('GS010', 'Femme T-Shirt In Stripe', 'p-Femme-T-Shirt-In-Stripe', 'Nautical striped cotton crewneck tee with reinforced collar and soft-washed finish.', 25.85, 'Women', ARRAY['women', 't-shirt', 'casual'], 4.80, 14, '[{"url": "images/product-10.jpg"}]'::jsonb, false, false),
    ('GS011', 'Herschel supply men', 'p-Herschel-supply-men', 'Modern tailored jacket designed for urban explorers with dual zip and water-resistant finish.', 63.16, 'Men', ARRAY['men', 'jacket', 'outerwear'], 4.88, 22, '[{"url": "images/product-11.jpg"}]'::jsonb, true, false),
    ('GS012', 'Herschel supply watch', 'p-Herschel-supply-watch', 'Modern minimalist quartz watch with brushed gunmetal case and quick-release strap.', 63.15, 'Watches', ARRAY['watches', 'minimalist', 'accessories'], 4.75, 17, '[{"url": "images/product-12.jpg"}]'::jsonb, false, false),
    ('GS013', 'T-Shirt with Sleeve', 'p-T-Shirt-with-Sleeve', 'Contemporary everyday basic tee with rolled cuff detailing and premium combed cotton feel.', 18.49, 'Women', ARRAY['women', 't-shirt', 'basics'], 4.60, 9, '[{"url": "images/product-13.jpg"}]'::jsonb, false, false),
    ('GS014', 'Pretty Little Thing', 'p-Pretty-Little-Thing', 'Elegant structured dress with subtle waist cinching and flowing hemline.', 54.79, 'Women', ARRAY['women', 'dress', 'party'], 4.82, 31, '[{"url": "images/product-14.jpg"}]'::jsonb, true, true),
    ('GS015', 'Mini Silver Mesh Watch', 'p-Mini-Silver-Mesh-Watch', 'Sleek silver mesh bracelet watch with mother-of-pearl dial and water resistance up to 30m.', 86.85, 'Watches', ARRAY['watches', 'silver', 'jewelry'], 4.92, 29, '[{"url": "images/product-15.jpg"}]'::jsonb, true, true),
    ('GS016', 'Square Neck Back', 'p-Square-Neck-Back', 'Chic square-neck bodysuit crafted from double-layered contour fabric for a sculpted fit.', 29.64, 'Women', ARRAY['women', 'bodysuit', 'basics'], 4.78, 16, '[{"url": "images/product-16.jpg"}]'::jsonb, false, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    rating = EXCLUDED.rating;

-- Seed Sample Verified Reviews
INSERT INTO public.reviews (product_name, reviewer_name, email, rating, comment, verified_purchase) VALUES
    ('Esprit Ruffle Shirt', 'Sai Ganesh', 'sai@ganeshstore.com', 5, 'This shirt exceeds all expectations! The fabric is incredibly soft and the ruffle detail is impeccably crafted.', true),
    ('Esprit Ruffle Shirt', 'Olivia Vance', 'olivia@vance.net', 5, 'Perfect fit and gorgeous silhouette. Arrived in just 2 days with standard delivery!', true),
    ('Classic Trench Coat', 'Alexander Wright', 'alex@wright.org', 5, 'A true luxury staple. The craftsmanship rivals coats 4x this price.', true),
    ('Vintage Inspired Classic', 'Marcus Aurelius', 'marcus@heritage.com', 5, 'Impeccable timepiece. Weight and leather strap feel absolutely premium.', true);
