-- ====================================================================
-- GANESHSTORE SUPABASE DATABASE SCHEMA MIGRATION SCRIPT
-- Copy and paste this script directly into the Supabase SQL Editor
-- ====================================================================

-- 1. Create Profiles Table (Direct Name & Phone login mapping / Firebase Sync)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY,
    full_name TEXT NOT NULL,
    phone_number TEXT,
    email TEXT UNIQUE,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable RLS for Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Anyone can manage profiles" ON public.profiles
    FOR ALL USING (true);


-- 2. Create Product Reviews Table (Globally Shared across all users!)
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name TEXT NOT NULL,
    reviewer_name TEXT NOT NULL,
    email TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable RLS for Reviews
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reviews are viewable by everyone" ON public.reviews
    FOR SELECT USING (true);

CREATE POLICY "Anyone can submit a review" ON public.reviews
    FOR INSERT WITH CHECK (true);


-- 3. Create Carts Table (Synced in the cloud)
CREATE TABLE IF NOT EXISTS public.carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
    product_name TEXT NOT NULL,
    price TEXT NOT NULL,
    image_url TEXT NOT NULL,
    quantity INTEGER DEFAULT 1 NOT NULL,
    size TEXT NOT NULL,
    color TEXT NOT NULL,
    link TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable RLS for Carts
ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can manage carts" ON public.carts
    FOR ALL USING (true);


-- 4. Create Wishlists Table (Synced in the cloud)
CREATE TABLE IF NOT EXISTS public.wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles ON DELETE CASCADE NOT NULL,
    product_name TEXT NOT NULL,
    price TEXT NOT NULL,
    image_url TEXT NOT NULL,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Enable RLS for Wishlists
ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can manage wishlists" ON public.wishlists
    FOR ALL USING (true);
