-- ====================================================================
-- GANESHSTORE ENTERPRISE SUPABASE DATABASE MIGRATION & SCHEMA
-- ====================================================================
-- Version: 2.0.0
-- Description: Complete enterprise database schema for GaneshStore,
-- including Profiles, Products, Reviews, Carts, Wishlists, Orders,
-- Newsletter Subscribers, Contact Inquiries, and Coupons with RLS,
-- performance indexes, automatic timestamp triggers, and seed data.
-- ====================================================================

-- 0. Helper Functions & Extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc'::text, NOW());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- 1. Profiles Table (User Accounts, Loyalty Points, Tiers & 2FA)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    full_name TEXT NOT NULL,
    email TEXT UNIQUE,
    phone_number TEXT,
    loyalty_tier TEXT DEFAULT 'Bronze' CHECK (loyalty_tier IN ('Bronze', 'Silver', 'Gold', 'Platinum')),
    loyalty_points INTEGER DEFAULT 100,
    two_factor_enabled BOOLEAN DEFAULT false,
    two_factor_secret TEXT,
    avatar_url TEXT,
    default_address JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles
    FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile" ON public.profiles
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can update their own profile" ON public.profiles
    FOR UPDATE USING (true);

CREATE TRIGGER set_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);
CREATE INDEX IF NOT EXISTS idx_profiles_phone ON public.profiles(phone_number);


-- 2. Products Catalog Table
CREATE TABLE IF NOT EXISTS public.products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    original_price NUMERIC(10, 2),
    category TEXT NOT NULL,
    subcategory TEXT,
    tags TEXT[] DEFAULT ARRAY[]::TEXT[],
    rating NUMERIC(3, 2) DEFAULT 5.00,
    reviews_count INTEGER DEFAULT 0,
    images JSONB DEFAULT '[]'::jsonb,
    sizes TEXT[] DEFAULT ARRAY['S', 'M', 'L', 'XL']::TEXT[],
    colors TEXT[] DEFAULT ARRAY['Default']::TEXT[],
    stock_quantity INTEGER DEFAULT 50,
    is_featured BOOLEAN DEFAULT false,
    is_trending BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Products are viewable by everyone" ON public.products
    FOR SELECT USING (true);

CREATE POLICY "Anyone can manage products" ON public.products
    FOR ALL USING (true);

CREATE TRIGGER set_products_updated_at
    BEFORE UPDATE ON public.products
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_products_category ON public.products(category);
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);


-- 3. Product Reviews Table (Globally Shared & Rating Aggregated)
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT REFERENCES public.products(id) ON DELETE CASCADE,
    product_name TEXT NOT NULL,
    reviewer_name TEXT NOT NULL,
    email TEXT NOT NULL,
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) NOT NULL,
    comment TEXT NOT NULL,
    verified_purchase BOOLEAN DEFAULT true,
    helpful_votes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reviews are viewable by everyone" ON public.reviews
    FOR SELECT USING (true);

CREATE POLICY "Anyone can submit a review" ON public.reviews
    FOR INSERT WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_reviews_product_name ON public.reviews(product_name);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews(product_id);


-- 4. Carts Table (Cloud Persistent Shopping Carts)
CREATE TABLE IF NOT EXISTS public.carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,
    items JSONB DEFAULT '[]'::jsonb NOT NULL,
    subtotal NUMERIC(10, 2) DEFAULT 0.00,
    total NUMERIC(10, 2) DEFAULT 0.00,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.carts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can manage carts" ON public.carts
    FOR ALL USING (true);

CREATE TRIGGER set_carts_updated_at
    BEFORE UPDATE ON public.carts
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_carts_user_id ON public.carts(user_id);


-- 5. Wishlists Table (Cloud Persistent Wishlists)
CREATE TABLE IF NOT EXISTS public.wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL UNIQUE,
    items JSONB DEFAULT '[]'::jsonb NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.wishlists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can manage wishlists" ON public.wishlists
    FOR ALL USING (true);

CREATE TRIGGER set_wishlists_updated_at
    BEFORE UPDATE ON public.wishlists
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_wishlists_user_id ON public.wishlists(user_id);


-- 6. Orders Table (E-commerce Checkout & Live Tracking)
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL UNIQUE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    customer_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    shipping_address TEXT NOT NULL,
    shipping_method TEXT DEFAULT 'Standard Delivery' NOT NULL,
    payment_method TEXT DEFAULT 'CARD' NOT NULL,
    payment_status TEXT DEFAULT 'COMPLETED' CHECK (payment_status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    order_status TEXT DEFAULT 'processing' CHECK (order_status IN ('placed', 'processing', 'shipped', 'out_for_delivery', 'delivered', 'cancelled')),
    tracking_number TEXT,
    estimated_delivery DATE,
    items JSONB NOT NULL,
    subtotal NUMERIC(10, 2) NOT NULL,
    discount NUMERIC(10, 2) DEFAULT 0.00 NOT NULL,
    shipping_fee NUMERIC(10, 2) DEFAULT 0.00 NOT NULL,
    tax NUMERIC(10, 2) DEFAULT 0.00 NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can manage orders" ON public.orders
    FOR ALL USING (true);

CREATE TRIGGER set_orders_updated_at
    BEFORE UPDATE ON public.orders
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE INDEX IF NOT EXISTS idx_orders_order_id ON public.orders(order_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_email ON public.orders(email);


-- 7. Newsletter Subscribers Table
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    source TEXT DEFAULT 'footer_newsletter',
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'unsubscribed')),
    subscribed_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can subscribe to newsletter" ON public.newsletter_subscribers
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Newsletter subscribers are viewable" ON public.newsletter_subscribers
    FOR SELECT USING (true);

CREATE INDEX IF NOT EXISTS idx_newsletter_email ON public.newsletter_subscribers(email);


-- 8. Contact Inquiries / Messages Table
CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT,
    message TEXT NOT NULL,
    status TEXT DEFAULT 'unread' CHECK (status IN ('unread', 'read', 'replied')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can submit contact message" ON public.contact_messages
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Contact messages viewable" ON public.contact_messages
    FOR SELECT USING (true);


-- 9. Coupons & Promotions Table
CREATE TABLE IF NOT EXISTS public.coupons (
    code TEXT PRIMARY KEY,
    discount_type TEXT DEFAULT 'percentage' CHECK (discount_type IN ('percentage', 'fixed', 'free_shipping')),
    discount_value NUMERIC(10, 2) NOT NULL,
    min_order_amount NUMERIC(10, 2) DEFAULT 0.00,
    max_discount NUMERIC(10, 2),
    is_active BOOLEAN DEFAULT true,
    valid_until TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Coupons are viewable by everyone" ON public.coupons
    FOR SELECT USING (true);


-- ====================================================================
-- INITIAL SEED DATA
-- ====================================================================

-- Seed Coupons
INSERT INTO public.coupons (code, discount_type, discount_value, min_order_amount, is_active) VALUES
    ('SAVE10', 'percentage', 10.00, 0.00, true),
    ('GANESH20', 'fixed', 20.00, 50.00, true),
    ('WELCOME10', 'percentage', 10.00, 0.00, true),
    ('FREESHIP', 'free_shipping', 0.00, 0.00, true)
ON CONFLICT (code) DO UPDATE SET is_active = true;

-- Seed Master Products
INSERT INTO public.products (id, name, slug, description, price, category, tags, rating, reviews_count, images, is_featured, is_trending) VALUES
    ('GS001', 'Esprit Ruffle Shirt', 'p-Esprit-Ruffle-Shirt', 'Ultra-breathable premium cotton ruffle shirt with meticulous stitching and modern relaxed fit.', 16.64, 'Women', ARRAY['women', 'fashion', 'shirt'], 4.90, 28, '[{"url": "images/product-01.jpg"}]'::jsonb, true, true),
    ('GS002', 'Herschel supply', 'p-Herschel-supply', 'Iconic minimalist everyday essential tailored for effortless style and maximum comfort.', 35.31, 'Women', ARRAY['women', 'fashion', 'top'], 4.80, 19, '[{"url": "images/product-02.jpg"}]'::jsonb, true, false),
    ('GS003', 'Only Check Trouser', 'p-Only-Check-Trouser', 'Tailored check trousers crafted from premium stretch fabric for smart-casual and formal elegance.', 25.50, 'Men', ARRAY['men', 'trouser', 'pants'], 4.85, 24, '[{"url": "images/product-03.jpg"}]'::jsonb, false, true),
    ('GS004', 'Classic Trench Coat', 'p-Classic-Trench-Coat', 'Signature double-breasted weatherproof trench coat with premium storm flap and waist belt.', 75.00, 'Women', ARRAY['women', 'coat', 'jacket'], 5.00, 42, '[{"url": "images/product-04.jpg"}]'::jsonb, true, true),
    ('GS005', 'Front Pocket Jumper', 'p-Front-Pocket-Jumper', 'Cozy knit jumper with front utility pocket detailing and ribbed cuff trims.', 34.75, 'Women', ARRAY['women', 'jumper', 'knitwear'], 4.75, 15, '[{"url": "images/product-05.jpg"}]'::jsonb, false, false),
    ('GS006', 'Vintage Inspired Classic', 'p-Vintage-Inspired-Classic', 'Timeless chronometer watch with genuine Italian leather strap and scratch-resistant sapphire crystal.', 93.20, 'Watches', ARRAY['watches', 'accessories', 'luxury'], 4.95, 36, '[{"url": "images/product-06.jpg"}]'::jsonb, true, true),
    ('GS007', 'Shirt in Stretch Cotton', 'p-Shirt-in-Stretch-Cotton', 'Refined stretch cotton button-up shirt engineered for clean lines and all-day flexibility.', 52.66, 'Women', ARRAY['women', 'shirt', 'formal'], 4.70, 11, '[{"url": "images/product-07.jpg"}]'::jsonb, false, false),
    ('GS008', 'Pieces Metallic Printed', 'p-Pieces-Metallic-Printed', 'Shimmering metallic printed party top designed for statement evening occasions.', 18.96, 'Women', ARRAY['women', 'top', 'metallic'], 4.65, 8, '[{"url": "images/product-08.jpg"}]'::jsonb, false, false),
    ('GS009', 'Converse All Star Hi Plimsolls', 'p-Converse-All-Star-Hi-Plimsolls', 'High-top canvas sneaker classic with vulcanized rubber sole and vintage ankle patch.', 75.00, 'Shoes', ARRAY['shoes', 'sneakers', 'footwear'], 4.90, 53, '[{"url": "images/product-09.jpg"}]'::jsonb, true, true),
    ('GS010', 'Femme T-Shirt In Stripe', 'p-Femme-T-Shirt-In-Stripe', 'Nautical striped cotton crewneck tee with reinforced collar and soft-washed finish.', 25.85, 'Women', ARRAY['women', 't-shirt', 'casual'], 4.80, 14, '[{"url": "images/product-10.jpg"}]'::jsonb, false, false),
    ('GS011', 'Herschel supply men', 'p-Herschel-supply-men', 'Modern tailored jacket designed for urban explorers with dual zip and water-resistant finish.', 63.16, 'Men', ARRAY['men', 'jacket', 'outerwear'], 4.88, 22, '[{"url": "images/product-11.jpg"}]'::jsonb, true, false),
    ('GS012', 'Herschel supply watch', 'p-Herschel-supply-watch', 'Modern minimalist quartz watch with brushed gunmetal case and quick-release strap.', 63.15, 'Watches', ARRAY['watches', 'minimalist', 'accessories'], 4.75, 17, '[{"url": "images/product-12.jpg"}]'::jsonb, false, false),
    ('GS013', 'T-Shirt with Sleeve', 'p-T-Shirt-with-Sleeve', 'Contemporary everyday basic tee with rolled cuff detailing and premium combed cotton feel.', 18.49, 'Women', ARRAY['women', 't-shirt', 'basics'], 4.60, 9, '[{"url": "images/product-13.jpg"}]'::jsonb, false, false),
    ('GS014', 'Pretty Little Thing', 'p-Pretty-Little-Thing', 'Elegant structured dress with subtle waist cinching and flowing hemline.', 54.79, 'Women', ARRAY['women', 'dress', 'party'], 4.82, 31, '[{"url": "images/product-14.jpg"}]'::jsonb, true, true),
    ('GS015', 'Mini Silver Mesh Watch', 'p-Mini-Silver-Mesh-Watch', 'Sleek silver mesh bracelet watch with mother-of-pearl dial and water resistance up to 30m.', 86.85, 'Watches', ARRAY['watches', 'silver', 'jewelry'], 4.92, 29, '[{"url": "images/product-15.jpg"}]'::jsonb, true, true),
    ('GS016', 'Square Neck Back', 'p-Square-Neck-Back', 'Chic square-neck bodysuit crafted from double-layered contour fabric for a sculpted fit.', 29.64, 'Women', ARRAY['women', 'bodysuit', 'basics'], 4.78, 16, '[{"url": "images/product-16.jpg"}]'::jsonb, false, false)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    price = EXCLUDED.price,
    rating = EXCLUDED.rating;

-- Seed Sample Verified Reviews
INSERT INTO public.reviews (product_name, reviewer_name, email, rating, comment, verified_purchase) VALUES
    ('Esprit Ruffle Shirt', 'Sai Ganesh', 'sai@ganeshstore.com', 5, 'This shirt exceeds all expectations! The fabric is incredibly soft and the ruffle detail is impeccably crafted.', true),
    ('Esprit Ruffle Shirt', 'Olivia Vance', 'olivia@vance.net', 5, 'Perfect fit and gorgeous silhouette. Arrived in just 2 days with standard delivery!', true),
    ('Classic Trench Coat', 'Alexander Wright', 'alex@wright.org', 5, 'A true luxury staple. The craftsmanship rivals coats 4x this price.', true),
    ('Vintage Inspired Classic', 'Marcus Aurelius', 'marcus@heritage.com', 5, 'Impeccable timepiece. Weight and leather strap feel absolutely premium.', true);
